name: Deploy to Gist
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'README.md'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Deploy to Gist
        uses: exuanbo/actions-deploy-gist@v1.1.4
        with:
          # Set personal access token for updating gist.
          token: ${{secrets.GIST_UPDATE_TOKEN}}
          # Set id of the gist to be updated.
          gist_id: 4f73149627006b57d51d581dbb09e0fe
          # Set description of the gist.
          gist_description: An Awesome list about all things related to portal
          # Set file name in the gist.
          gist_file_name: bfportal-2042-awesome.md
          # Set path of the file to be deployed.
          file_path: README.md
          # Set file type of the file to be deployed.
          file_type: text
